name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  checks: write
  pull-requests: write

jobs:
  build_and_test:
    name: Build advent-of-code solutions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest
      - uses: taiki-e/install-action@llvm-cov
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: nextest
      - name: Export Coverage Report
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: report --codecov --output-path ./coverage.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: ./coverage.xml,
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            target/nextest/default/*.xml